name: Auto Deploy with Rollback to Docker Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCKER_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 165.232.188.143 >> ~/.ssh/known_hosts

      - name: Deploy to Docker Server with Rollback
        run: |
          ssh root@165.232.188.143 << 'EOF'
            set -e

            echo "===> STEP 1: BACKUP current container and image"
            docker ps -q --filter "name=schoolerp_app" | grep . && docker commit schoolerp_app schoolerp_backup:latest || echo "No running container to backup"

            echo "===> STEP 2: Entering project directory"
            cd /root/docker-stacks/schoolerp

            echo "===> STEP 3: Pulling latest code"
            git config user.email 'sales@britexcbe.com'
            git config user.name 'Vkysrn-ux'
            git config pull.rebase false
            git pull origin main

            echo "===> STEP 4: Stopping existing containers"
            docker-compose down --remove-orphans || true

            echo "===> STEP 5: Pruning old Docker resources"
            docker system prune -af || true
            docker volume prune -f || true

            echo "===> STEP 6: Building new image"
            docker-compose build --no-cache

            echo "===> STEP 7: Starting new containers"
            docker-compose up -d

            echo "===> STEP 8: Checking health endpoint"
            sleep 10
            curl -f http://localhost:3000/health || (echo "Deployment failed, rolling back..." && docker rm -f $(docker ps -aq --filter name=schoolerp_app) && docker run -d --name schoolerp_app -p 3000:3000 schoolerp_backup:latest && exit 1)

            echo "✅ Deployment Successful"
          EOF

      - name: On Failure - Show error log
        if: failure()
        run: echo "❌ Deployment failed. Last working container restored. Check logs on the server."
